# Generated by Django 3.0.5 on 2020-05-05 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='retailer',
            field=models.CharField(default='emag', max_length=200),
            preserve_default=False,
        ),
    ]
