# Generated by Django 3.0.5 on 2020-05-06 09:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shopper', '0002_product_retailer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='date_scrapped',
        ),
        migrations.RemoveField(
            model_name='product',
            name='old_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.CreateModel(
            name='Product_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('old_price', models.FloatField()),
                ('date_scrapped', models.DateTimeField(default=django.utils.timezone.now)),
                ('link_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopper.Product')),
            ],
        ),
    ]
