# Generated by Django 3.0.5 on 2020-05-06 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopper', '0003_auto_20200506_1227'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_info',
            old_name='date_scrapped',
            new_name='date_scraped',
        ),
        migrations.RenameField(
            model_name='product_info',
            old_name='link_ref',
            new_name='product_base',
        ),
    ]
