# Generated by Django 3.0.5 on 2020-05-28 23:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shopper', '0004_auto_20200506_1519'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Saved_Product',
        ),
        migrations.RenameModel(
            old_name='Product_Info',
            new_name='Saved_Product_Info',
        ),
        migrations.CreateModel(
            name='Searched_Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('link', models.TextField()),
                ('retailer', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('old_price', models.FloatField()),
                ('date_scraped', models.DateTimeField(default=django.utils.timezone.now)),
                ('searcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
