# Generated by Django 3.0.5 on 2020-06-14 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopper', '0005_auto_20200529_0216'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Searched_Product',
        ),
    ]
