# Generated by Django 3.0.5 on 2020-06-14 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopper', '0007_auto_20200614_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saved_product',
            name='link',
            field=models.URLField(),
        ),
    ]
