# Generated by Django 3.0.5 on 2020-06-14 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopper', '0008_auto_20200614_2252'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saved_product_info',
            old_name='date_scraped',
            new_name='date',
        ),
    ]
