# Generated by Django 3.0.5 on 2020-06-16 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopper', '0010_auto_20200616_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saved_product',
            name='retailer',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='saved_product',
            name='searcher',
            field=models.TextField(),
        ),
    ]
