# Generated by Django 3.0.5 on 2020-06-20 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shopper', '0011_auto_20200616_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saved_product',
            name='searcher',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
