# Generated by Django 3.0.5 on 2020-06-20 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopper', '0013_auto_20200620_1351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saved_product',
            name='searcher',
        ),
        migrations.AlterField(
            model_name='saved_product_info',
            name='product_base',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infos', to='shopper.Saved_Product'),
        ),
        migrations.CreateModel(
            name='CustomUser_NestedField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.TextField()),
                ('product_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='shopper.Saved_Product')),
            ],
        ),
    ]
